version: '3.8'

services:
  postgresql:
    container_name: golang-api-good-practices-postgresql
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER:     localuser
      POSTGRES_PASSWORD: the-secret
      POSTGRES_HOST:     postgresql
      POSTGRES_PORT:     5432
      POSTGRES_DB:       hotel
      PGDATA:            /tmp
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
#  backend:
#    container_name: golang-api-good-practices-backend
#    env_file:
#      - .env
#    depends_on:
#      - postgresql
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      POSTGRES_USER:     localuser
#      POSTGRES_PASSWORD: the-secret
#      POSTGRES_HOST:     postgresql
#      POSTGRES_PORT:     5432
#      POSTGRES_DB:       hotel
#    ports:
#      - "7000:7000"
#    volumes:
#      - "./:/opt/app"
##    command: sh -c "go run main.go"
#    command: sh -c "sleep infinity"

volumes:
  postgresql-data: