version: '3'

tasks:
  dev-start:
    cmds:
      - migrate -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable -path store/migrations up
      - go run main.go
